### ISSUE TITLE
Request for Open Source License🙏

### ISSUE THREAD

**Issue by arpagon** [karliky/turrero#2]
Hello @karliky 

I am writing to express my support for the El Turrero Post project and to encourage you to consider using an open source license for the website. By using a license like the MIT or Apache v2, you will be able to share your work with the community and allow others to build upon it.

Using an open source license will also ensure that your work is protected and that others can use it legally. It will also help to promote collaboration and innovation within the field of complexity science.

I hope you will consider this suggestion and look forward to seeing the El Turrero Post project thrive under an open source license.

Best,

**Comment by karliky** [comment]
Historically, all projects I made have the "Unlicense" project, that's what I like to use.

I've just added it to the repo https://github.com/karliky/turrero/blob/main/LICENSE.md

**Comment by arpagon** [comment]
Thanks, Carlos.
